package com.ebicep.warlords.util.pve;

import javax.annotation.Nonnull;

public enum VariantSkullID implements Skull {

    DROWNED_VARIANT("NzBkOTIyODgzYzA2MDEwYmMzNmVlZmYwNjUyN2QzOTA1MzVjZmRhNjZhNDk2OGMwZjRlZDBkMjRmNGRmNDcwZiJ9fX0="),
    PIRATE_CAPTAIN("YmM1MzYyNzg4NjQyYzM2ZDRiZTBjNmIxMmI1MTYxZWEyNTdiMmY5YjU5ZDhkZTQwYzFhNzBjMGM2NjgxYWMxYiJ9fX0="),
    MUSHROOM_CREATURE("MmQwNzA0NmRkNjMyYTgyNGM1NTMwOGYwMWI2NGE4N2VjOGVmYWM5MjdiZGQwNWFmOGQ4ZjIzYzEyOTA5NDExYSJ9fX0="),
    FROZEN_SKELETON("NGRmZDE4MzU5MDA3MWJjYjE4M2NmYzk3ZjZjYjNiZWIyNzA2NjhjNWZlYTcxMTk5MDRmYThmYzU1MTE1NzYwMiJ9fX0="),
    SKULL_KNIGHT("NTJiODA1MWQ4ODAyZGYwOTViN2MyZGE2NjEyNGU2MzMzYjFmOTNhM2NhYTljNWFmZWI2YjE2NTM0ZDQyMzk4ZCJ9fX0="),
    PLAGUE_DOCTOR("OWQzNDIwYzk5ZDhiMDc5NWRmNGRhYzNhZmI5Y2ZiYTViMjA4NTRlZmIxYmUzNWYwMGFmYTgzYmIzOWU1YTAzMiJ9fX0="),
    CULTIST("ODJiOTlhMDMzNjEzZjAyYjJiOWFjMzk5NWFmYTgzNDczYjljM2E1ZWMwODUwZGJiNzc3Yjk5NmRjNjMxYjM1OSJ9fX0="),
    DIVER_HELMET("NmQ5NDJjYjFmNmM5MWZkMmY5Mzc1ZGI1N2VjMjhmZjJhZWJmMzgxNWVlOTZhMzc3MWZjOTlmMGI1ZTJlYzllNCJ9fX0="),
    ANUBIS("MmM4YzIyODRmZWIyZDk1ZjAxMDA3ZmRmMDM4MGExZjAzYWE0OWQ2ZmY0NGZiNTkzOWZkZjNjN2YyODMwNWJkOCJ9fX0="),
    GLOWING_ZOMBIE("YTY4MTdiZTliZmY5ZmRmMTYxZjBkZDk1NjhkODIwMWI5MzkzYTk4MjkwMTY2ZDhmM2QxY2YzYjVjN2FmOTE1OCJ9fX0=");

    private final String textureId;

    VariantSkullID(@Nonnull String textureId) {
        this.textureId = textureId;
    }

    @Override
    public String getTextureID() {
        return "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUv" + textureId;
    }
}
