package com.ebicep.warlords.util;

public enum ClassesSkillBoosts {
    FIREBALL("Fireball",
            "§7Increases the damage you\n§7deal with Fireball by 20%",
            "§aIncreases the damage you\n§adeal with Fireball by §c20%"),
    FLAME_BURST("Flame Burst",
            "§7Increases the damage you\n§7deal with Flame Burst by\n§720%",
            "§aIncreases the damage you\n§adeal with Flame Burst by\n§c20%"),
    FROST_BOLT("Frostbolt",
            "§7Increases the damage you\n§7deal with Frostbolt by\n§720%",
            "§aIncreases the damage you\n§adeal with Frostbolt by\n§c20%"),
    FREEZING_BREATH("Freezing Breath",
            "§7Increase the damage you\n§7deal with Freezing Breath\n§7by 20%",
            "§aIncrease the damage you\n§adeal with Freezing Breath\n§aby §c20%"),
    WATER_BOLT("Water Bolt",
            "§7Increases the amount of\n§7health you restore with\n§7Water Bolt by 20%",
            "§aIncreases the amount of\n§ahealth you restore with\n§aWater Bolt by §c20%"),
    WATER_BREATH("Water Breath",
            "§7Increases the amount of\n§7health you restore with\n§7Water Breath by 20%",
            "§aIncreases the amount of\n§ahealth you restore with\n§aWater Breath by §c20%"),
    WOUNDING_STRKE("Wounding Strike",
            "§7Increase the damage you\n§7deal with Wounding Strike\n§7by 20%",
            "§aIncrease the damage you\n§adeal with Wounding Strike\n§aby §c20%"),
    SEISMIC_WAVE("Seismic Wave",
            "§7Increase the damage you\n§7deal with Seismic Wave by\n§720%",
            "§aIncrease the damage you\n§adeal with Seismic Wave by\n§c20%"),
    GROUND_SLAM("Ground Slam",
            "§7Increase the damage you\n§7deal with Ground Slam by\n§720%",
            "§aIncrease the damage you\n§adeal with Ground Slam by\n§c20%"),
    CRIPPLING_STRIKE("Crippling Strike",
            "§7Increase the damage you\n§7deal with Crippling Strike\n§7by 20%",
            "§aIncrease the damage you\n§adeal with Crippling Strike\n§aby §c20%"),
    ORBS_OF_LIFE("Orbs of Life",
            "§7Increases the amount of\n§7health you restore with\n§7Orbs of Life by 20%",
            "§aIncreases the amount of\n§ahealth you restore with\n§aOrbs of Life by §c20%"),
    AVENGER_STRIKE("Avenger's Strike",
            "§7Increase the damage you\n§7deal with Avenger's Strike\n§7by 20%",
            "§aIncrease the damage you\n§adeal with Avenger's Strike\n§aby §c20%"),
    CRUSADER_STRIKE("Crusader's Strike",
            "§7Increase the damage you\n§7deal with Crusader's Strike\n§7by 20%",
            "§aIncrease the damage you\n§adeal with Crusader's Strike\n§aby §c20%"),
    CONSECRATE("Consecrate",
            "§7Increase the damage you\n§7deal with Consecrate by 20%",
            "§aIncrease the damage you\n§adeal with Consecrate by §c20%"),
    HOLY_RADIANCE("Holy Radiance",
            "§7Increases the amount of\n§7health you restore with\n§7Holy Radiance by 20%",
            "§aIncreases the amount of\n§ahealth you restore with\n§aHoly Radiance by §c20%"),
    HAMMER_OF_LIGHT("Hammer of Light",
            "§7Increases the amount of\n§7health you restore with\n§7Hammer of Light by 20%",
            "§aIncreases the amount of\n§ahealth you restore with\n§aHammer of Light by §c20%"),
    LIGHTNING_BOLT("Lightning Bolt",
            "§7Increase the damage you\n§7deal with Lightning Bolt by\n§720%",
            "§aIncrease the damage you\n§adeal with Lightning Bolt by\n§c20%"),
    CHAIN_LIGHTNING("Chain Lightning",
            "§7Increase the damage you\n§7deal with Chain Lightning\n§7by 20%",
            "§aIncrease the damage you\n§adeal with Chain Lightning\n§aby §c20%"),
    WINDFURY_WEAPON("Windfury Weapon",
            "§7Increase the damage you\n§7deal with Windfury Weapon\n§7by 20%",
            "§aIncrease the damage you\n§adeal with Windfury Weapon\n§aby §c20%"),
    FALLEN_SOULS("Fallen Souls",
            "§7Increase the damage you\n§7deal with Fallen Souls by\n§720%",
            "§aIncrease the damage you\n§adeal with Fallen Souls by\n§c20%"),
    SPIRIT_LINK("Spirit Link",
            "§7Increase the damage you\n§7deal with Spirit Link by\n§720%",
            "§aIncrease the damage you\n§adeal with Spirit Link by\n§c20%"),
    EARTHEN_SPIKE("Earthen Spike",
            "§7Increase the damage you\n§7deal with Earthen Spike by\n§720%",
            "§aIncrease the damage you\n§adeal with Earthen Spike by\n§c20%"),
    BOULDER("Boulder",
            "§7Increase the damage you\n§7deal with Boulder by 20%",
            "§aIncrease the damage you\n§adeal with Boulder by 20%"),
    CHAIN_HEAL("Chain Heal",
            "§7Increases the amount of\n§7health you restore with\n§7Chain Heal by 20%",
            "§aIncreases the amount of\n§ahealth you restore with\n§aChain Heal by §c20%"),
    NONE("FUCK",
            "??? What am i doing here",
            "why am i alive");

    public final String name;
    public final String description;
    public final String selectedDescription;

    ClassesSkillBoosts(String name, String description, String selectedDescription) {
        this.name = name;
        this.description = description;
        this.selectedDescription = selectedDescription;
    }
}