package com.ebicep.warlords.database.repositories.player.pojos.pve.events.modes.gardenofhesperides.theacropolis;


import com.ebicep.warlords.database.repositories.games.pojos.pve.events.gardenofhesperides.theacropolis.DatabaseGamePlayerPvEEventTheAcropolis;
import com.ebicep.warlords.database.repositories.games.pojos.pve.events.gardenofhesperides.theacropolis.DatabaseGamePvEEventTheAcropolis;
import com.ebicep.warlords.database.repositories.player.pojos.pve.events.PvEEventDatabaseStatInformation;

public class PvEEventGardenOfHesperidesAcropolisDatabaseStatInformation extends PvEEventDatabaseStatInformation<DatabaseGamePvEEventTheAcropolis, DatabaseGamePlayerPvEEventTheAcropolis> implements PvEEventGardenOfHesperidesTheAcropolisStats {

}
