package com.ebicep.warlords.database.repositories.player.pojos.pve.events.modes.libraryarchives.grimoiresgraveyard.classes;

import com.ebicep.warlords.database.repositories.player.pojos.pve.events.modes.libraryarchives.grimoiresgraveyard.PvEEventLibraryArchivesGrimoiresGraveyardDatabaseStatInformation;

public class DatabaseBasePvEEventLibraryArchivesGrimoiresGraveyard extends PvEEventLibraryArchivesGrimoiresGraveyardDatabaseStatInformation {

}
