package com.ebicep.warlords.player;

import com.ebicep.warlords.classes.abilties.*;

public enum ClassesSkillBoosts {
    FIREBALL("Fireball",
            "§7Increases the damage you\n§7deal with Fireball by 20%",
            "§aIncreases the damage you\n§adeal with Fireball by §c20%",
            Fireball.class),
    FLAME_BURST("Flame Burst",
            "§7Increases the damage you\n§7deal with Flame Burst by\n§720%",
            "§aIncreases the damage you\n§adeal with Flame Burst by\n§c20%",
            FlameBurst.class),
    FROST_BOLT("Frostbolt",
            "§7Increases the damage you\n§7deal with Frostbolt by\n§720%",
            "§aIncreases the damage you\n§adeal with Frostbolt by\n§c20%",
            FrostBolt.class),
    FREEZING_BREATH("Freezing Breath",
            "§7Increase the damage you\n§7deal with Freezing Breath\n§7by 20%",
            "§aIncrease the damage you\n§adeal with Freezing Breath\n§aby §c20%",
            FreezingBreath.class),
    WATER_BOLT("Water Bolt",
            "§7Increases the amount of\n§7health you restore with\n§7Water Bolt by 20%",
            "§aIncreases the amount of\n§ahealth you restore with\n§aWater Bolt by §c20%",
            WaterBolt.class),
    WATER_BREATH("Water Breath",
            "§7Increases the amount of\n§7health you restore with\n§7Water Breath by 20%",
            "§aIncreases the amount of\n§ahealth you restore with\n§aWater Breath by §c20%",
            WaterBreath.class),
    HEALING_RAIN("Healing Rain",
            "§7Increases the amount of\n§7health you restore with\n§7Healing Rain by 30%",
            "§aIncreases the amount of\n§ahealth you restore with\n§aHealing Rain by §c30%",
            HealingRain.class),
    WOUNDING_STRIKE_BERSERKER("Wounding Strike",
            "§7Increase the damage you\n§7deal with Wounding Strike\n§7by 20%",
            "§aIncrease the damage you\n§adeal with Wounding Strike\n§aby §c20%",
            WoundingStrikeBerserker.class),
    WOUNDING_STRIKE_DEFENDER("Wounding Strike",
            "§7Increase the damage you\n§7deal with Wounding Strike\n§7by 20%",
            "§aIncrease the damage you\n§adeal with Wounding Strike\n§aby §c20%",
            WoundingStrikeDefender.class),
    SEISMIC_WAVE("Seismic Wave",
            "§7Increase the damage you\n§7deal with Seismic Wave by\n§720%",
            "§aIncrease the damage you\n§adeal with Seismic Wave by\n§c20%",
            SeismicWave.class),
    GROUND_SLAM("Ground Slam",
            "§7Increase the damage you\n§7deal with Ground Slam by\n§720%",
            "§aIncrease the damage you\n§adeal with Ground Slam by\n§c20%",
            GroundSlam.class),
    CRIPPLING_STRIKE("Crippling Strike",
            "§7Increase the damage you\n§7deal with Crippling Strike\n§7by 20%",
            "§aIncrease the damage you\n§adeal with Crippling Strike\n§aby §c20%",
            CripplingStrike.class),
    RECKLESS_CHARGE("Reckless Charge",
            "§7Increase the damage you\n§7deal with Reckless Charge by\n§720%",
            "§aIncrease the damage you\n§adeal with Reckless Charge by\n§c20%",
            RecklessCharge.class),
    ORBS_OF_LIFE("Orbs of Life",
            "§7Increases the amount of\n§7health you restore with\n§7Orbs of Life by 20%",
            "§aIncreases the amount of\n§ahealth you restore with\n§aOrbs of Life by §c20%",
            OrbsOfLife.class),
    AVENGER_STRIKE("Avenger's Strike",
            "§7Increase the damage you\n§7deal with Avenger's Strike\n§7by 20%",
            "§aIncrease the damage you\n§adeal with Avenger's Strike\n§aby §c20%",
            AvengersStrike.class),
    CRUSADER_STRIKE("Crusader's Strike",
            "§7Increase the damage you\n§7deal with Crusader's Strike\n§7by 20%",
            "§aIncrease the damage you\n§adeal with Crusader's Strike\n§aby §c20%",
            CrusadersStrike.class),
    PROTECTOR_STRIKE("Protector's Strike",
            "§7Increase the amount of damage\n§7you convert into healing with\n§7Protector's Strike by 20%",
            "§aIncrease the amount of damage\n§ayou convert into healing with\n§aProtector's Strike by §c20%",
            ProtectorsStrike.class),
    CONSECRATE("Consecrate",
            "§7Increase the damage you\n§7deal with Consecrate by 20%",
            "§aIncrease the damage you\n§adeal with Consecrate by §c20%",
            Consecrate.class),
    HOLY_RADIANCE("Holy Radiance",
            "§7Increases the amount of\n§7health you restore with\n§7Holy Radiance by 20%",
            "§aIncreases the amount of\n§ahealth you restore with\n§aHoly Radiance by §c20%",
            HolyRadiance.class),
    HAMMER_OF_LIGHT("Hammer of Light",
            "§7Increases the amount of\n§7health you restore with\n§7Hammer of Light by 40%",
            "§aIncreases the amount of\n§ahealth you restore with\n§aHammer of Light by §c40%",
            HammerOfLight.class),
    LIGHTNING_BOLT("Lightning Bolt",
            "§7Increase the damage you\n§7deal with Lightning Bolt by\n§720%",
            "§aIncrease the damage you\n§adeal with Lightning Bolt by\n§c20%",
            LightningBolt.class),
    CHAIN_LIGHTNING("Chain Lightning",
            "§7Increase the damage you\n§7deal with Chain Lightning\n§7by 20%",
            "§aIncrease the damage you\n§adeal with Chain Lightning\n§aby §c20%",
            ChainLightning.class),
    WINDFURY_WEAPON("Windfury Weapon",
            "§7Increase the damage you\n§7deal with Windfury Weapon\n§7by 20%",
            "§aIncrease the damage you\n§adeal with Windfury Weapon\n§aby §c20%",
            Windfury.class),
    CAPACITOR_TOTEM("Capacitor Totem",
            "§7Increase the damage you\n§7deal with Capacitor Totem\n§7by 30%",
            "§aIncrease the damage you\n§adeal with Capacitor Totem\n§aby §c30%",
            CapacitorTotem.class),
    FALLEN_SOULS("Fallen Souls",
            "§7Increase the damage you\n§7deal with Fallen Souls by\n§720%",
            "§aIncrease the damage you\n§adeal with Fallen Souls by\n§c20%",
            FallenSouls.class),
    SPIRIT_LINK("Spirit Link",
            "§7Increase the damage you\n§7deal with Spirit Link by\n§720%",
            "§aIncrease the damage you\n§adeal with Spirit Link by\n§c20%",
            SpiritLink.class),
    EARTHEN_SPIKE("Earthen Spike",
            "§7Increase the damage you\n§7deal with Earthen Spike by\n§720%",
            "§aIncrease the damage you\n§adeal with Earthen Spike by\n§c20%",
            EarthenSpike.class),
    BOULDER("Boulder",
            "§7Increase the damage you\n§7deal with Boulder by 20%",
            "§aIncrease the damage you\n§adeal with Boulder by §c20%",
            Boulder.class),
    CHAIN_HEAL("Chain Heal",
            "§7Increases the amount of\n§7health you restore with\n§7Chain Heal by 20%",
            "§aIncreases the amount of\n§ahealth you restore with\n§aChain Heal by §c20%",
            ChainHeal.class),
    HEALING_TOTEM("Healing Totem",
            "§7Increases the amount of\n§7health you restore with\n§7Healing Totem by 40%",
            "§aIncreases the amount of\n§ahealth you restore with\n§aHealing Totem by §c40%",
            HealingTotem.class);

    public final String name;
    public final String description;
    public final String selectedDescription;
    public final Class ability;

    ClassesSkillBoosts(String name, String description, String selectedDescription, Class ability) {
        this.name = name;
        this.description = description;
        this.selectedDescription = selectedDescription;
        this.ability = ability;
    }
}